
name: "directories_and_excel"

description: "Updates data files and commits"

runs:
  using: composite
  steps:
    - name: Collect any new commits
      shell: bash
      run: |
        git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Regularize directories
      shell: bash
      run: python3 scripts/regularize_directories.py

    - name: Update CSVs
      shell: bash
      run: python3 scripts/export_csvs.py

    - name: Update SBOL
      shell: bash
      run: python3 scripts/export_sbol.py

    - name: Commit changes, ready to push
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add */views
        git diff-index --quiet HEAD . || git commit -m "Automatically update exports"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}