name: "build_packages"

description: "Build and validate final packages"
runs:
  using: composite
  steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Collect any new commits
      shell: bash
      run: |
        git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Collate packages
      shell: bash
      run: python3 scripts/collate_packages.py

    - name: Create vector build plans
      shell: bash
      run: python3 scripts/expand_combinations.py

    - name: Generate markdown from packages
      shell: bash
      run: python3 scripts/generate_markdown.py

    - name: Commit changes, ready to push
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add */views/*.nt */README.md
        git diff-index --quiet HEAD . || git commit -m "Collate and summarize packages"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}